CREATE TABLE USERLOGIN (
						USERID INT PRIMARY KEY IDENTITY(1001,1),	
						USERNAME VARCHAR(MAX) NOT NULL,
						DATEOFBIRTH DATE ,
						AGE			INT,
						USERADDRESS     VARCHAR(MAX) DEFAULT 'Unknown',
						)
CREATE TABLE ACCOUNTINFO(
						ACCOUNTID INT PRIMARY KEY IDENTITY(1,1)	,
						ACCOUNTNUMBER   DECIMAL(5,0),
						PIN				INT,
						USERID			INT NOT NULL,
						FOREIGN KEY (USERID) REFERENCES USERLOGIN(USERID)
)
ALTER TABLE ACCOUNTINFO
ALTER COLUMN PIN VARCHAR(5) 
INSERT INTO ACCOUNTINFO VALUES(12345,'0001',1001)
SELECT * FROM USERLOGIN
SELECT * FROM ACCOUNTINFO

